export class Service {
  serviceType: string | undefined;
  serviceName: string | undefined;
  serviceShortName: string | undefined;
  description: string | undefined;
  startPurpose: string | undefined;
  developerName: string | undefined;
  dateStart: string | undefined;
  endPurpose: string | undefined;
  dateEnd: string | undefined;
  status: string | undefined;
  isIS: boolean | undefined;
  isHasCoordinate: boolean | undefined;
  isService: boolean | undefined;
  criticalValue: number | undefined;
  subRows: Service[] | undefined;
}

export const data: Service[] = [
  {
    'serviceType': 'ППО',
    'serviceName': 'Сервис технической поддержки пользователей',
    'serviceShortName': '',
    'description': '',
    'startPurpose': '',
    'developerName': '',
    'dateStart': '',
    'endPurpose': '',
    'dateEnd': '',
    'status': 'ПЭ',
    'isIS': false,
    'isHasCoordinate': false,
    'isService': false,
    'criticalValue': 1,
    subRows: [],
  },
  {
    'serviceType': 'ПО',
    'serviceName': '1С: Предприятие',
    'serviceShortName': '1С: Предприятие',
    'description': '',
    'startPurpose': '',
    'developerName': '',
    'dateStart': '',
    'endPurpose': '',
    'dateEnd': '',
    'status': 'ПЭ',
    'isIS': false,
    'isHasCoordinate': false,
    'isService': false,
    'criticalValue': 3,
    subRows: [
      {
        'serviceType': 'ППО',
        'serviceName': '1С: Выписки 7.7',
        'serviceShortName': '1С: Выписки 7.7',
        'description': 'Автоматизированная система  для автоматизации процесса разноски банковских выписок из Банк-клиентов в ПК Казна, 1С:Бухгалтерия и ПК Реализация.',
        'startPurpose': '',
        'developerName': 'ООО "1С", АО "Алтайэнергосбыт"',
        'dateStart': '01.01.2009',
        'endPurpose': '',
        'dateEnd': '01.06.2013',
        'status': 'Выведена из эксплуатации',
        'isIS': true,
        'isHasCoordinate': true,
        'isService': true,
        'criticalValue': 2,
        subRows: [],
      },
      {
        'serviceType': 'ППО',
        'serviceName': '1С: Автотранспорт',
        'serviceShortName': '1С: Автотранспорт',
        'description': 'Система  для автоматизации процессов контроля затрат по содержанию автомобилей, контроля соблюдения скоростного режима, контроля выезда автомобилей за границы закрепленных геозон, контроль работы водителей в выходные дни. ',
        'startPurpose': 'Приказ № 587 от 28.12.2016; Приказ № 398/1 от 01.09.2016;  Приказ № АЭС/353 06.06.2024 (перевод БД на СУБД Postgres Pro)  ',
        'developerName': 'ООО "1С", АО "Алтайэнергосбыт"',
        'dateStart': '01.09.2016',
        'endPurpose': '',
        'dateEnd': '',
        'status': 'ПЭ',
        'isIS': true,
        'isHasCoordinate': true,
        'isService': true,
        'criticalValue': 2,
        subRows: [],
      },
      {
        'serviceType': 'ППО',
        'serviceName': '1С: Управление торговлей',
        'serviceShortName': '1С: Управление торговлей',
        'description': 'Программный комплекс предназначенный для автоматизации ведения учета дополнительных платных сервисов. ',
        'startPurpose': '',
        'developerName': 'ООО "1С", АО "Алтайэнергосбыт"',
        'dateStart': '01.08.2014',
        'endPurpose': '',
        'dateEnd': '',
        'status': 'ПЭ',
        'isIS': true,
        'isHasCoordinate': true,
        'isService': true,
        'criticalValue': 1,
        subRows: [],
      },
      {
        'serviceType': 'ППО',
        'serviceName': '1С: Бухгалтерия 8.2 (до 31.07.2014)',
        'serviceShortName': '1С: Бухгалтерия 8.2',
        'description': 'Автоматизированная система  для автоматизации  задач бухгалтерского и налогового учета.',
        'startPurpose': '',
        'developerName': 'ООО "1С", АО "Алтайэнергосбыт"',
        'dateStart': '01.01.2012',
        'endPurpose': '',
        'dateEnd': '31.07.2014',
        'status': 'АЭ',
        'isIS': true,
        'isHasCoordinate': true,
        'isService': true,
        'criticalValue': 3,
        subRows: [],
      },
      {
        'serviceType': 'ПО',
        'serviceName': 'Агентские договора',
        'serviceShortName': 'Агентские договора',
        'description': '',
        'startPurpose': '',
        'developerName': '',
        'dateStart': '',
        'endPurpose': '',
        'dateEnd': '',
        'status': '',
        'isIS': false,
        'isHasCoordinate': false,
        'isService': false,
        'criticalValue': 3,
        subRows: [
          {
            'serviceType': 'ПО',
            'serviceName': '1С: ЖКХ (МУП "Теплосбыт" - ФЛ)',
            'serviceShortName': '1С: ЖКХ (МУП "Теплосбыт" - ФЛ)',
            'description': '',
            'startPurpose': '',
            'developerName': '',
            'dateStart': '01.07.2020',
            'endPurpose': '',
            'dateEnd': '',
            'status': 'АЭ',
            'isIS': true,
            'isHasCoordinate': true,
            'isService': true,
            'criticalValue': 1,
            subRows: [],
          },
          {
            'serviceType': 'ПО',
            'serviceName': '1С: ЖКХ (МУП "Теплосбыт" - ЮЛ)',
            'serviceShortName': '1С: ЖКХ (МУП "Теплосбыт" - ЮЛ',
            'description': 'Расчет тепла по ЮЛ',
            'startPurpose': '',
            'developerName': '',
            'dateStart': '01.07.2020',
            'endPurpose': '',
            'dateEnd': '',
            'status': 'АЭ',
            'isIS': true,
            'isHasCoordinate': true,
            'isService': true,
            'criticalValue': 3,
            subRows: [],
          },
          {
            'serviceType': 'ППО',
            'serviceName': '1С: МУП "Волчихинский КС"',
            'serviceShortName': '1С: МУП "Волчихинский КС"',
            'description': '',
            'startPurpose': '',
            'developerName': '',
            'dateStart': '',
            'endPurpose': '',
            'dateEnd': '',
            'status': 'АЭ',
            'isIS': true,
            'isHasCoordinate': true,
            'isService': true,
            'criticalValue': 3,
            subRows: [],
          },
        ],
      },
    ],
  },
  ]
