/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/article/{id}": {
    get: operations["getById"];
    put: operations["update"];
  };
  "/api/ordertask/path": {
    post: operations["postMethodName"];
  };
  "/api/order": {
    get: operations["getAll"];
    post: operations["create"];
  };
  "/api/article": {
    get: operations["getAll_1"];
    post: operations["create_1"];
  };
  "/api/approveuser": {
    get: operations["getAll_2"];
    post: operations["create_2"];
  };
  "/api/approve": {
    get: operations["getAll_3"];
    post: operations["create_3"];
  };
  "/api/ordertask/{id}": {
    get: operations["getById_1"];
    patch: operations["update_1"];
  };
  "/api/order/{id}": {
    get: operations["getById_2"];
    delete: operations["delete"];
    patch: operations["update_2"];
  };
  "/api/order/{id}/status": {
    patch: operations["updateStatus"];
  };
  "/api/worktype": {
    get: operations["getAll_4"];
  };
  "/api/worktype/{id}": {
    get: operations["getById_3"];
  };
  "/api/work": {
    get: operations["getAll_5"];
  };
  "/api/work/{id}": {
    get: operations["getById_4"];
  };
  "/api/userrole": {
    get: operations["getAll_6"];
  };
  "/api/userrole/{id}": {
    get: operations["getById_5"];
  };
  "/api/user": {
    get: operations["getAll_7"];
  };
  "/api/user/{id}": {
    get: operations["getById_6"];
  };
  "/api/taskstate": {
    get: operations["getAll_8"];
  };
  "/api/taskstate/{id}": {
    get: operations["getById_7"];
  };
  "/api/sklad": {
    get: operations["getAll_9"];
  };
  "/api/sklad/{id}": {
    get: operations["getById_8"];
  };
  "/api/servicetype": {
    get: operations["getAll_10"];
  };
  "/api/servicetype/{id}": {
    get: operations["getById_9"];
  };
  "/api/servicestate": {
    get: operations["getAll_11"];
  };
  "/api/servicestate/{id}": {
    get: operations["getById_10"];
  };
  "/api/service": {
    get: operations["getAll_12"];
  };
  "/api/service/{id}": {
    get: operations["getById_11"];
  };
  "/api/scale": {
    get: operations["getAll_13"];
  };
  "/api/scale/{id}": {
    get: operations["getById_12"];
  };
  "/api/role": {
    get: operations["getAll_14"];
  };
  "/api/role/{id}": {
    get: operations["getById_13"];
  };
  "/api/recepient": {
    get: operations["getAll_15"];
  };
  "/api/recepient/{id}": {
    get: operations["getById_14"];
  };
  "/api/podr": {
    get: operations["getAll_16"];
  };
  "/api/podr/{id}": {
    get: operations["getById_15"];
  };
  "/api/ordertype": {
    get: operations["getAll_17"];
  };
  "/api/ordertype/{id}": {
    get: operations["getById_16"];
  };
  "/api/ordertask": {
    get: operations["getAll_18"];
  };
  "/api/orderstate": {
    get: operations["getAll_19"];
  };
  "/api/orderstate/{id}": {
    get: operations["getById_17"];
  };
  "/api/ordersource": {
    get: operations["getAll_20"];
  };
  "/api/ordersource/{id}": {
    get: operations["getById_18"];
  };
  "/api/orderpriority": {
    get: operations["getAll_21"];
  };
  "/api/orderpriority/{id}": {
    get: operations["getById_19"];
  };
  "/api/ordermessage": {
    get: operations["getAll_22"];
  };
  "/api/ordermessage/{id}": {
    get: operations["getById_20"];
  };
  "/api/orderbinding": {
    get: operations["getAll_23"];
  };
  "/api/orderbinding/{id}": {
    get: operations["getById_21"];
  };
  "/api/orderbinding/orders/{orderId}/files": {
    get: operations["getFiles"];
  };
  "/api/orderbinding/files/{id}": {
    get: operations["downloadFile"];
  };
  "/api/operation": {
    get: operations["getAll_24"];
  };
  "/api/operation/{id}": {
    get: operations["getById_22"];
  };
  "/api/new": {
    get: operations["getAll_25"];
  };
  "/api/new/{id}": {
    get: operations["getById_23"];
  };
  "/api/menu": {
    get: operations["getAll_26"];
  };
  "/api/menu/{id}": {
    get: operations["getById_24"];
  };
  "/api/mailingtype": {
    get: operations["getAll_27"];
  };
  "/api/mailingtype/{id}": {
    get: operations["getById_25"];
  };
  "/api/group": {
    get: operations["getAll_28"];
  };
  "/api/group/{id}": {
    get: operations["getById_26"];
  };
  "/api/function": {
    get: operations["getAll_29"];
  };
  "/api/function/{id}": {
    get: operations["getById_27"];
  };
  "/api/factlocation": {
    get: operations["getAll_30"];
  };
  "/api/factlocation/{id}": {
    get: operations["getById_28"];
  };
  "/api/exptype": {
    get: operations["getAll_31"];
  };
  "/api/exptype/{id}": {
    get: operations["getById_29"];
  };
  "/api/effect": {
    get: operations["getAll_32"];
  };
  "/api/effect/{id}": {
    get: operations["getById_30"];
  };
  "/api/document": {
    get: operations["getAll_33"];
  };
  "/api/document/{id}": {
    get: operations["getById_31"];
  };
  "/api/catitemstate": {
    get: operations["getAll_34"];
  };
  "/api/catitemstate/{id}": {
    get: operations["getById_32"];
  };
  "/api/catalogitemuserrole": {
    get: operations["getAll_35"];
  };
  "/api/catalogitemuserrole/{id}": {
    get: operations["getById_33"];
  };
  "/api/catalogitem": {
    get: operations["getAll_36"];
  };
  "/api/catalogitem/{id}": {
    get: operations["getById_34"];
  };
  "/api/catalogarhdata": {
    get: operations["getAll_37"];
  };
  "/api/catalogarhdata/{id}": {
    get: operations["getById_35"];
  };
  "/api/catalogarh": {
    get: operations["getAll_38"];
  };
  "/api/catalogarh/{id}": {
    get: operations["getById_36"];
  };
  "/api/authority": {
    get: operations["getAll_39"];
  };
  "/api/authority/{id}": {
    get: operations["getById_37"];
  };
  "/api/articlecategory": {
    get: operations["getAll_40"];
  };
  "/api/articlecategory/{id}": {
    get: operations["getById_38"];
  };
  "/api/approveuser/{id}": {
    get: operations["getById_39"];
  };
  "/api/approve/{id}": {
    get: operations["getById_40"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ArticleDTO: {
      title?: string;
      content?: string;
      /** Format: date-time */
      dateCreated?: string;
      /** Format: int32 */
      idArticleCategory?: number;
    };
    Article: {
      /** Format: int32 */
      idArticle?: number;
      title?: string;
      content?: string;
      /** Format: date-time */
      dateCreated?: string;
      articleCategory?: components["schemas"]["ArticleCategory"];
      userCreator?: components["schemas"]["User"];
    };
    ArticleCategory: {
      /** Format: int32 */
      idArticleCategory?: number;
      name?: string;
    };
    Authority: {
      /** Format: int32 */
      idAuthority?: number;
      authority?: string;
      description?: string;
      users?: components["schemas"]["User"][];
    };
    FactLocation: {
      /** Format: int32 */
      idFactLocation?: number;
      name?: string;
      podrs?: components["schemas"]["Podr"][];
    };
    Group: {
      /** Format: int32 */
      idGroup?: number;
      responsibleUser?: components["schemas"]["User"];
      name?: string;
      name1cDoc?: string;
      description?: string;
      users?: components["schemas"]["User"][];
    };
    Podr: {
      /** Format: int32 */
      idPodr?: number;
      name?: string;
      podrParent?: components["schemas"]["Podr"];
      id1c?: string;
      isDeleted?: boolean;
      /** Format: int32 */
      por?: number;
      factLocations?: components["schemas"]["FactLocation"][];
    };
    User: {
      /** Format: int32 */
      idItUser?: number;
      loginAd?: string;
      emailAd?: string;
      telAd?: string;
      fio1c?: string;
      podr?: components["schemas"]["Podr"];
      dolzh1c?: string;
      tabNum1c?: string;
      /** Format: date */
      dateCreate?: string;
      /** Format: date */
      dateModern?: string;
      isUser?: boolean;
      /** Format: date */
      datePrin?: string;
      /** Format: date */
      dateUvol?: string;
      agreementType?: string;
      fizLico?: string;
      state1c?: string;
      ctiUser?: string;
      ctiPassword?: string;
      crmUser?: string;
      crmPassword?: string;
      interAd?: boolean;
      /** Format: int32 */
      grade?: number;
      groups?: components["schemas"]["Group"][];
      authorities?: components["schemas"]["Authority"][];
    };
    OrderCreateRequestDTO: {
      name: string;
      /** Format: int32 */
      idService: number;
      /** Format: int32 */
      idCatItem: number;
      /** Format: int32 */
      idInitiator: number;
      /** Format: int32 */
      idOrderType: number;
      description: string;
      comment?: string;
      /** Format: int32 */
      idOrderSource?: number;
      /** Format: date-time */
      dateFinishPlan?: string;
      /** Format: date-time */
      dateTechReturn?: string;
    };
    OrderResponseDTO: {
      /** Format: int32 */
      idOrder: number;
      /** Format: int32 */
      nomer: number;
      name: string;
      description: string;
      /** Format: date-time */
      dateCreated: string;
      /** Format: date-time */
      dateFinishPlan: string | null;
      /** Format: date-time */
      dateFinishFact: string | null;
      /** Format: date-time */
      datePostpone: string | null;
      /** Format: date-time */
      dateTechReturn: string | null;
      comment: string | null;
      resultText: string | null;
      /** Format: int32 */
      orderParentId: number | null;
      /** Format: int32 */
      initiatorId: number;
      /** Format: int32 */
      creatorId: number;
      /** Format: int32 */
      dispatcherId: number | null;
      dispatcherFio: string | null;
      /** Format: int32 */
      executorId: number | null;
      executorFio: string | null;
      /** Format: int32 */
      orderTypeId: number;
      orderTypeName: string;
      /** Format: int32 */
      catalogItemId: number;
      catalogItemName: string;
      /** Format: int32 */
      serviceId: number;
      serviceFullname: string;
      /** Format: int32 */
      orderStateId: number;
      orderStateName: string;
      /** Format: int32 */
      orderPriorityId: number;
      orderPriorityName: string;
      /** Format: int32 */
      orderSourceId: number;
      orderSourceName: string;
    };
    ApproveUserCreateRequestDTO: {
      /** Format: int32 */
      idApprove: number;
      /** Format: int32 */
      idUser: number;
      /** Format: int32 */
      idUserRole?: number;
      /** Format: int32 */
      state?: number;
      /** Format: int32 */
      idApproveUserParent?: number;
      /** Format: date-time */
      datePlan?: string;
      taskText?: string;
    };
    ApproveUserResponseDTO: {
      /** Format: int32 */
      idApproveUser?: number;
      /** Format: int32 */
      idApprove?: number;
      /** Format: int32 */
      idUser?: number;
      /** Format: int32 */
      idUserRole?: number;
      /** Format: int32 */
      state?: number;
      resultText?: string;
      /** Format: int32 */
      idApproveUserParent?: number;
      /** Format: date-time */
      datePlan?: string;
      /** Format: date-time */
      dateFact?: string;
      taskText?: string;
    };
    ApproveCreateRequestDTO: {
      /** Format: int32 */
      idOrder: number;
      name: string;
      /** Format: int32 */
      idUserCreator: number;
      /** Format: int32 */
      idApproveState: number;
      /** Format: date-time */
      datePlan?: string;
      taskText?: string;
    };
    ApproveResponseDTO: {
      /** Format: int32 */
      idApprove?: number;
      /** Format: int32 */
      idOrder?: number;
      name?: string;
      /** Format: int32 */
      idUserCreator?: number;
      flagApproved?: boolean;
      /** Format: date-time */
      dateCreated?: string;
      /** Format: date-time */
      datePlan?: string;
      /** Format: int32 */
      idApproveState?: number;
      /** Format: date-time */
      dateFact?: string;
      taskText?: string;
    };
    TaskUpdateDTO: {
      /** Format: int32 */
      idOrder?: number | null;
      /** Format: int32 */
      idOrderTaskParent?: number | null;
      /** Format: int32 */
      idWork?: number | null;
      /** Format: int32 */
      idExecutor?: number | null;
      /** Format: date-time */
      dateFinishPlan?: string | null;
      /** Format: date-time */
      dateFinishFact?: string | null;
      description?: string | null;
      closeParentCheck?: boolean | null;
      /** Format: int32 */
      idTaskState?: number | null;
      /** Format: int32 */
      idCreator?: number | null;
      resultText?: string | null;
    };
    CatalogItem: {
      /** Format: int32 */
      idCatitem?: number;
      /** Format: int32 */
      idService?: number;
      catitemParent?: components["schemas"]["CatalogItem"];
      expType?: components["schemas"]["ExpType"];
      expBasis?: string;
      /** Format: date */
      expDate?: string;
      nomer?: string;
      name?: string;
      description?: string;
      info?: string;
      effect?: components["schemas"]["Effect"];
      scale?: components["schemas"]["Scale"];
      expOutBasis?: string;
      /** Format: date */
      expOutDate?: string;
      catitemState?: components["schemas"]["CatitemState"];
      services?: components["schemas"]["Serv"][];
    };
    CatitemState: {
      /** Format: int32 */
      idCatitemState?: number;
      name?: string;
    };
    Effect: {
      /** Format: int32 */
      idEffect?: number;
      name?: string;
    };
    ExpType: {
      /** Format: int32 */
      idExpType?: number;
      name?: string;
    };
    Order: {
      /** Format: int32 */
      idOrder?: number;
      /** Format: int32 */
      nomer?: number;
      name?: string;
      description?: string;
      /** Format: date-time */
      dateCreated?: string;
      /** Format: date-time */
      dateFinishPlan?: string;
      /** Format: date-time */
      dateFinishFact?: string;
      /** Format: date-time */
      datePostpone?: string;
      /** Format: date-time */
      dateTechReturn?: string;
      comment?: string;
      orderParent?: components["schemas"]["Order"];
      orderType?: components["schemas"]["OrderType"];
      catalogItem?: components["schemas"]["CatalogItem"];
      service?: components["schemas"]["Serv"];
      orderState?: components["schemas"]["OrderState"];
      orderPriority?: components["schemas"]["OrderPriority"];
      creator?: components["schemas"]["User"];
      initiator?: components["schemas"]["User"];
      dispatcher?: components["schemas"]["User"];
      executor?: components["schemas"]["User"];
      orderSource?: components["schemas"]["OrderSource"];
      resultText?: string;
    };
    OrderPriority: {
      /** Format: int32 */
      idOrderPriority?: number;
      name?: string;
      color?: string;
    };
    OrderSource: {
      /** Format: int32 */
      idOrderSource?: number;
      name?: string;
    };
    OrderState: {
      /** Format: int32 */
      idOrderState?: number;
      name?: string;
    };
    OrderTask: {
      /** Format: int32 */
      idOrderTask?: number;
      order?: components["schemas"]["Order"];
      orderTaskParent?: components["schemas"]["OrderTask"];
      work?: components["schemas"]["Work"];
      executor?: components["schemas"]["User"];
      /** Format: date-time */
      dateFinishPlan?: string;
      /** Format: date-time */
      dateFinishFact?: string;
      description?: string;
      closeParentCheck?: boolean;
      taskState?: components["schemas"]["TaskState"];
      /** Format: date-time */
      dateCreated?: string;
      creator?: components["schemas"]["User"];
      resultText?: string;
    };
    OrderType: {
      /** Format: int32 */
      idOrderType?: number;
      name?: string;
      available?: boolean;
    };
    Scale: {
      /** Format: int32 */
      idScale?: number;
      name?: string;
    };
    Serv: {
      /** Format: int32 */
      idService?: number;
      fullname?: string;
      sname?: string;
      description?: string;
      developer?: string;
      /** Format: date */
      dateS?: string;
      /** Format: date */
      dateF?: string;
      priznakIs?: boolean;
      serviceType?: components["schemas"]["ServiceType"];
      serviceState?: components["schemas"]["ServiceState"];
      expType?: components["schemas"]["ExpType"];
      serviceParent?: components["schemas"]["Serv"];
      isNeedApproval?: boolean;
      isService?: boolean;
      /** Format: int32 */
      businessCritical?: number;
      basisS?: string;
      catalogItems?: components["schemas"]["CatalogItem"][];
    };
    ServiceState: {
      /** Format: int32 */
      idServiceState?: number;
      name?: string;
    };
    ServiceType: {
      /** Format: int32 */
      idServiceType?: number;
      name?: string;
      fullname?: string;
    };
    TaskState: {
      /** Format: int32 */
      idTaskState?: number;
      name?: string;
    };
    Work: {
      /** Format: int32 */
      idWork?: number;
      workParent?: components["schemas"]["Work"];
      catitem?: components["schemas"]["CatalogItem"];
      service?: components["schemas"]["Serv"];
      group?: components["schemas"]["Group"];
      workType?: components["schemas"]["WorkType"];
      remark?: string;
      podr?: components["schemas"]["Podr"];
    };
    WorkType: {
      /** Format: int32 */
      idWorkType?: number;
      name?: string;
      description?: string;
    };
    OrderUpdateDTO: {
      name?: string | null;
      description?: string | null;
      /** Format: date-time */
      dateFinishPlan?: string | null;
      /** Format: date-time */
      dateFinishFact?: string | null;
      /** Format: date-time */
      dateTechReturn?: string | null;
      /** Format: int32 */
      idOrderParent?: number | null;
      /** Format: int32 */
      idOrderType?: number | null;
      /** Format: int32 */
      idCatItem?: number | null;
      /** Format: int32 */
      idService?: number | null;
      /** Format: int32 */
      idOrderPriority?: number | null;
      /** Format: int32 */
      idOrderState?: number | null;
      /** Format: int32 */
      idCreator?: number | null;
      /** Format: int32 */
      idInitiator?: number | null;
      /** Format: int32 */
      idDispatcher?: number | null;
      /** Format: int32 */
      idExecutor?: number | null;
      /** Format: int32 */
      idOrderSource?: number | null;
      resultText?: string | null;
      /** Format: date-time */
      datePostpone?: string | null;
      comment?: string | null;
    };
    OrderStatusUpdateDTO: {
      /** Format: int32 */
      idOrderState?: number;
    };
    UserRole: {
      /** Format: int32 */
      idUserRole?: number;
      name?: string;
    };
    UserResponseDTO: {
      /** Format: int32 */
      idItUser?: number;
      loginAd?: string;
      emailAd?: string;
      telAd?: string;
      fio1c?: string;
      /** Format: int32 */
      podrId?: number;
      dolzh1c?: string;
      tabNum1c?: string;
      /** Format: date */
      dateCreate?: string;
      /** Format: date */
      dateModern?: string;
      isUser?: boolean;
      /** Format: date */
      datePrin?: string;
      /** Format: date */
      dateUvol?: string;
      agreementType?: string;
      fizLico?: string;
      state1c?: string;
      interAd?: boolean;
      /** Format: int32 */
      grade?: number;
      groupIds?: number[];
      authorityIds?: number[];
    };
    Sklad: {
      /** Format: int32 */
      idSklad?: number;
      name?: string;
      podr?: components["schemas"]["Podr"];
    };
    ServResponseDTO: {
      /** Format: int32 */
      idService?: number;
      fullname?: string;
      sname?: string;
      description?: string;
      developer?: string;
      /** Format: date */
      dateS?: string;
      /** Format: date */
      dateF?: string;
      priznakIs?: boolean;
      /** Format: int32 */
      serviceTypeId?: number;
      /** Format: int32 */
      serviceStateId?: number;
      /** Format: int32 */
      expTypeId?: number;
      /** Format: int32 */
      serviceParentId?: number;
      isNeedApproval?: boolean;
      isService?: boolean;
      /** Format: int32 */
      businessCritical?: number;
      basisS?: string;
    };
    Function: {
      /** Format: int32 */
      idFunction?: number;
      name?: string;
      description?: string;
      service?: components["schemas"]["Serv"];
      /** Format: int32 */
      accLevel?: number;
    };
    Role: {
      /** Format: int32 */
      idRole?: number;
      name?: string;
      description?: string;
      function?: components["schemas"]["Function"];
    };
    MailingType: {
      /** Format: int32 */
      idMailingType?: number;
      name?: string;
    };
    Recepient: {
      /** Format: int32 */
      idRecepient?: number;
      user?: components["schemas"]["User"];
      mailingType?: components["schemas"]["MailingType"];
    };
    PodrResponseDTO: {
      /** Format: int32 */
      idPodr?: number;
      name?: string;
      /** Format: int32 */
      parentId?: number;
      id1c?: string;
      isDeleted?: boolean;
      /** Format: int32 */
      por?: number;
      factLocationIds?: number[];
    };
    OrderMessage: {
      /** Format: int32 */
      idOrderMessage?: number;
      /** Format: date-time */
      dateCreated?: string;
      text?: string;
      order?: components["schemas"]["Order"];
      user?: components["schemas"]["User"];
      orderTask?: components["schemas"]["OrderTask"];
    };
    OrderBinding: {
      /** Format: int32 */
      idOrderBinding?: number;
      path?: string;
      order?: components["schemas"]["Order"];
      /** Format: date-time */
      dateCreated?: string;
      user?: components["schemas"]["User"];
      name?: string;
    };
    OrderBindingDTO: {
      /** Format: int32 */
      id?: number;
      name?: string;
      /** Format: date-time */
      dateCreated?: string;
    };
    Operation: {
      /** Format: int32 */
      idOperation?: number;
      name?: string;
      description?: string;
      function?: components["schemas"]["Function"];
    };
    New: {
      /** Format: int32 */
      idNew?: number;
      name?: string;
      /** Format: date-time */
      dateS?: string;
      description?: string;
      serviceEntity?: components["schemas"]["Serv"];
    };
    Menu: {
      /** Format: int32 */
      idMenu?: number;
      name?: string;
      description?: string;
      /** Format: int32 */
      accLevel?: number;
      function?: components["schemas"]["Function"];
    };
    GroupResponseDTO: {
      /** Format: int32 */
      idGroup?: number;
      name?: string;
      name1cDoc?: string;
      description?: string;
      /** Format: int32 */
      idResponsibleUser?: number;
    };
    FactLocationResponseDTO: {
      /** Format: int32 */
      idFactLocation?: number;
      name?: string;
    };
    Document: {
      /** Format: int32 */
      idDocument?: number;
      name?: string;
      type?: string;
      /** Format: byte */
      content?: string;
      newEntity?: components["schemas"]["New"];
    };
    CatalogItemUserRoleResponseDTO: {
      /** Format: int32 */
      idCatitemUserRole?: number;
      /** Format: int32 */
      catalogItemId?: number;
      /** Format: int32 */
      userId?: number;
      /** Format: int32 */
      podrId?: number;
      /** Format: int32 */
      userRoleId?: number;
      /** Format: int32 */
      serviceId?: number;
    };
    CatalogItemResponseDTO: {
      /** Format: int32 */
      idCatitem?: number;
      nomer?: string;
      name?: string;
      description?: string;
      info?: string;
      expBasis?: string;
      /** Format: date */
      expDate?: string;
      expOutBasis?: string;
      /** Format: date */
      expOutDate?: string;
      /** Format: int32 */
      serviceId?: number;
      /** Format: int32 */
      parentId?: number;
      /** Format: int32 */
      expTypeId?: number;
      /** Format: int32 */
      effectId?: number;
      /** Format: int32 */
      scaleId?: number;
      /** Format: int32 */
      catitemStateId?: number;
    };
    CatalogArh: {
      /** Format: int32 */
      idArh?: number;
      /** Format: date-time */
      dateCreated?: string;
      /** Format: int32 */
      userCreatorId?: number;
      remark?: string;
    };
    CatalogArhData: {
      /** Format: int32 */
      idData?: number;
      catalogArh?: components["schemas"]["CatalogArh"];
      /** Format: int32 */
      oldPk?: number;
      nomer?: string;
      name?: string;
      description?: string;
      org?: string;
      podr?: string;
      fioFz?: string;
      fioCu?: string;
      fioSm?: string;
      state?: string;
      expBasis?: string;
      /** Format: date-time */
      expDate?: string;
      scale?: string;
      effect?: string;
      info?: string;
    };
    AuthorityResponseDTO: {
      /** Format: int32 */
      idAuthority?: number;
      authority?: string;
      description?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  getById: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Article"];
        };
      };
    };
  };
  update: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArticleDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Article"];
        };
      };
    };
  };
  postMethodName: {
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": string;
        };
      };
    };
  };
  getAll: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderResponseDTO"][];
        };
      };
    };
  };
  create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderCreateRequestDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderResponseDTO"];
        };
      };
    };
  };
  getAll_1: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Article"][];
        };
      };
    };
  };
  create_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArticleDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Article"];
        };
      };
    };
  };
  getAll_2: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApproveUserResponseDTO"][];
        };
      };
    };
  };
  create_2: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApproveUserCreateRequestDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApproveUserResponseDTO"];
        };
      };
    };
  };
  getAll_3: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApproveResponseDTO"][];
        };
      };
    };
  };
  create_3: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApproveCreateRequestDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApproveResponseDTO"];
        };
      };
    };
  };
  getById_1: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderTask"];
        };
      };
    };
  };
  update_1: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskUpdateDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderTask"];
        };
      };
    };
  };
  getById_2: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderResponseDTO"];
        };
      };
    };
  };
  delete: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  update_2: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderUpdateDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderResponseDTO"];
        };
      };
    };
  };
  updateStatus: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrderStatusUpdateDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderResponseDTO"];
        };
      };
    };
  };
  getAll_4: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["WorkType"][];
        };
      };
    };
  };
  getById_3: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["WorkType"];
        };
      };
    };
  };
  getAll_5: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Work"][];
        };
      };
    };
  };
  getById_4: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Work"];
        };
      };
    };
  };
  getAll_6: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserRole"][];
        };
      };
    };
  };
  getById_5: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserRole"];
        };
      };
    };
  };
  getAll_7: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserResponseDTO"][];
        };
      };
    };
  };
  getById_6: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserResponseDTO"];
        };
      };
    };
  };
  getAll_8: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TaskState"][];
        };
      };
    };
  };
  getById_7: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TaskState"];
        };
      };
    };
  };
  getAll_9: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Sklad"][];
        };
      };
    };
  };
  getById_8: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Sklad"];
        };
      };
    };
  };
  getAll_10: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ServiceType"][];
        };
      };
    };
  };
  getById_9: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ServiceType"];
        };
      };
    };
  };
  getAll_11: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ServiceState"][];
        };
      };
    };
  };
  getById_10: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ServiceState"];
        };
      };
    };
  };
  getAll_12: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ServResponseDTO"][];
        };
      };
    };
  };
  getById_11: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ServResponseDTO"];
        };
      };
    };
  };
  getAll_13: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Scale"][];
        };
      };
    };
  };
  getById_12: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Scale"];
        };
      };
    };
  };
  getAll_14: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Role"][];
        };
      };
    };
  };
  getById_13: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Role"];
        };
      };
    };
  };
  getAll_15: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Recepient"][];
        };
      };
    };
  };
  getById_14: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Recepient"];
        };
      };
    };
  };
  getAll_16: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PodrResponseDTO"][];
        };
      };
    };
  };
  getById_15: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PodrResponseDTO"];
        };
      };
    };
  };
  getAll_17: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderType"][];
        };
      };
    };
  };
  getById_16: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderType"];
        };
      };
    };
  };
  getAll_18: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderTask"][];
        };
      };
    };
  };
  getAll_19: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderState"][];
        };
      };
    };
  };
  getById_17: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderState"];
        };
      };
    };
  };
  getAll_20: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderSource"][];
        };
      };
    };
  };
  getById_18: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderSource"];
        };
      };
    };
  };
  getAll_21: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderPriority"][];
        };
      };
    };
  };
  getById_19: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderPriority"];
        };
      };
    };
  };
  getAll_22: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderMessage"][];
        };
      };
    };
  };
  getById_20: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderMessage"];
        };
      };
    };
  };
  getAll_23: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderBinding"][];
        };
      };
    };
  };
  getById_21: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderBinding"];
        };
      };
    };
  };
  getFiles: {
    parameters: {
      path: {
        orderId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OrderBindingDTO"][];
        };
      };
    };
  };
  downloadFile: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": string;
        };
      };
    };
  };
  getAll_24: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Operation"][];
        };
      };
    };
  };
  getById_22: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Operation"];
        };
      };
    };
  };
  getAll_25: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["New"][];
        };
      };
    };
  };
  getById_23: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["New"];
        };
      };
    };
  };
  getAll_26: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Menu"][];
        };
      };
    };
  };
  getById_24: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Menu"];
        };
      };
    };
  };
  getAll_27: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["MailingType"][];
        };
      };
    };
  };
  getById_25: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["MailingType"];
        };
      };
    };
  };
  getAll_28: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["GroupResponseDTO"][];
        };
      };
    };
  };
  getById_26: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["GroupResponseDTO"];
        };
      };
    };
  };
  getAll_29: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Function"][];
        };
      };
    };
  };
  getById_27: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Function"];
        };
      };
    };
  };
  getAll_30: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["FactLocationResponseDTO"][];
        };
      };
    };
  };
  getById_28: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["FactLocationResponseDTO"];
        };
      };
    };
  };
  getAll_31: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ExpType"][];
        };
      };
    };
  };
  getById_29: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ExpType"];
        };
      };
    };
  };
  getAll_32: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Effect"][];
        };
      };
    };
  };
  getById_30: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Effect"];
        };
      };
    };
  };
  getAll_33: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Document"][];
        };
      };
    };
  };
  getById_31: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Document"];
        };
      };
    };
  };
  getAll_34: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CatitemState"][];
        };
      };
    };
  };
  getById_32: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CatitemState"];
        };
      };
    };
  };
  getAll_35: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CatalogItemUserRoleResponseDTO"][];
        };
      };
    };
  };
  getById_33: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CatalogItemUserRoleResponseDTO"];
        };
      };
    };
  };
  getAll_36: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CatalogItemResponseDTO"][];
        };
      };
    };
  };
  getById_34: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CatalogItemResponseDTO"];
        };
      };
    };
  };
  getAll_37: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CatalogArhData"][];
        };
      };
    };
  };
  getById_35: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CatalogArhData"];
        };
      };
    };
  };
  getAll_38: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CatalogArh"][];
        };
      };
    };
  };
  getById_36: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CatalogArh"];
        };
      };
    };
  };
  getAll_39: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AuthorityResponseDTO"][];
        };
      };
    };
  };
  getById_37: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AuthorityResponseDTO"];
        };
      };
    };
  };
  getAll_40: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ArticleCategory"][];
        };
      };
    };
  };
  getById_38: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ArticleCategory"];
        };
      };
    };
  };
  getById_39: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApproveUserResponseDTO"];
        };
      };
    };
  };
  getById_40: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ApproveResponseDTO"];
        };
      };
    };
  };
}
